CREATE DATABASE  DB_RESTAURANTE;
USE DB_RESTAURANTE;
CREATE TABLE TB_LOGIN(
ID INT PRIMARY KEY AUTO_INCREMENT,
LOGIN VARCHAR(30) UNIQUE NOT NULL,
SENHA VARCHAR(30) NOT NULL
);
INSERT into TB_LOGIN(login,senha)
VALUES
('Leone','1234');