CREATE DATABASE  DB_RESTAURANTE;
USE DB_RESTAURANTE;
CREATE TABLE TB_LOGIN(
ID INT PRIMARY KEY identity(1,1),
usuario VARCHAR(30) UNIQUE NOT NULL,
SENHA VARCHAR(30) NOT NULL
);
INSERT into TB_LOGIN(usuario,senha)
VALUES
('Leone','1234');
CREATE TABLE TB_FUNCIONARIOS(
NOME VARCHAR (20)NOT NULL,
RG VARCHAR(30)NOT NULL,
CPF VARCHAR(30) NOT NULL,
ENDERECO VARCHAR (25)NOT NULL,
NUMERO VARCHAR (25)NOT NULL,
BAIRRO VARCHAR (25)NOT NULL,
AGENCIA VARCHAR (25)NOT NULL,
CONTA VARCHAR (25)NOT NULL,
TELEFONE VARCHAR (25)NOT NULL,
CIDADE VARCHAR (25)NOT NULL,

);